### ISSUE TITLE
need help please

### ISSUE THREAD

**Issue by smallprogram** [GuillaumeFalourd/open-issue-action#3]
hi, @GuillaumeFalourd 
I use this action for repo, but something wrong, can you teach me how to fix? thank you

https://github.com/smallprogram/OpenWrtAction/runs/8095631030?check_suite_focus=true

**Comment by GuillaumeFalourd** [comment]
Hi @smallprogram , thank you for opening this issue! 🚀 

For what I understand looking at the log, it seems your self-hosted runner doesn't have Docker installed.

It's mandatory to have Docker installed on the runner to use this action, as it's a [Docker contain action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action).

**Comment by smallprogram** [comment]
> Hi @smallprogram , thank you for opening this issue! 🚀
> 
> For what I understand looking at the log, it seems your self-hosted runner doesn't have Docker installed.
> 
> It's mandatory to have Docker installed on the runner to use this action, as it's a [Docker contain action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action).

thank you, I will try

**Comment by smallprogram** [comment]
I am a Docker newbie, thank you for your reply, although there are still some questions, but I closed this issue first, thank you again
